### ISSUE TITLE
短信内容错误

### ISSUE THREAD

**Issue by kil-x** [xiaoyuanhost/TranspondSms#1]
正常的短信内容，
![2019-12-09_091853](https://user-images.githubusercontent.com/43434624/70400273-066c4780-1a65-11ea-88e9-6475e4a7ba14.png)
使用邮件接收的内容，出现了内容错乱，（内容一多就错乱）
![2019-12-09 -1](https://user-images.githubusercontent.com/43434624/70400283-1f74f880-1a65-11ea-88b9-3dd6330489bc.png)
钉钉收到的内容
![2019-12-09_092135](https://user-images.githubusercontent.com/43434624/70400325-67941b00-1a65-11ea-89ea-bc6560848331.png)

**Comment by xiaoyuanhost** [comment]
这个最新版本有修复，升级试下
