### ISSUE TITLE
原生安卓无法获取信息

### ISSUE THREAD

**Issue by alkaid-ops** [xiaoyuanhost/TranspondSms#13]
lineage-17.1 安卓10.0
MK90 安卓9.0
在所有权限都给予的情况下，无法监听短信，webhook测试正常。
猜测原生安卓拥有更强的隐私保护功能。

**Comment by sy1412** [comment]
我的SONY XZ1 安卓9也是

**Comment by L245T** [comment]
lg g7 系统版本 G710ULM20d 安卓9.0
同样在给了所有权限，webhook正常的情况下无法进行监听短信

**Comment by xifengxi** [comment]
不知道你们解决没有，我手机上”接收“短信的权限要单独打开才行
