### ISSUE TITLE
很好的软件，有个新想法分享

### ISSUE THREAD

**Issue by huangzi959** [xiaoyuanhost/TranspondSms#7]
目前我是配置了邮箱，主卡放在备用机，主力机用流量卡，主力机接收到信息需要打开QQ在进入邮箱，有点麻烦。不知道能不能添加一个手机收到短信后POST给配置网址这样的功能，这样我只要浏览器打开页面就可以看到信息了。

**Comment by xiaoyuanhost** [comment]
as your wish!! 如你所愿！！
浏览器作为网络设备兼容性最强的存在，确实比安装使用邮箱更方便
之前考虑到安全和隐私问题没有实现
这次这个版本给出了这个实现，网页后端可以使用[消息通知](https://msg.allmything.com)，或者自己寻求其他实现实现
